### ISSUE TITLE
Error with optional parameters `github-app` and `github-token`

### ISSUE THREAD

**Issue by agokulravikumar** [browserstack/github-actions#43]
Encountering an error while using the BrowserStack GitHub Actions. It seems that the optional parameters `github-app` and `github-token` are not being respected, leading to the following error:

`Error: Action Failed: Error: Invalid input for 'github-app'. Must be a valid string.`

**Steps to Reproduce:**

1. Set up a GitHub Actions workflow with the following configuration:
```
- name: BrowserStack GitHub Actions
  uses: browserstack/github-actions@master
  with:
    # Not providing github-app or github-token
    ...
```
2. Trigger the workflow.

**Expected Behavior:** The action should run without errors even if `github-app` and `github-token` are not provided since they are marked as optional.

**Actual Behavior:** Receiving an error indicating that `github-app` must be a valid string, even when it is not provided.

**Environment:**

GitHub Actions workflow file
Action version: master

**Additional Context:**

Verified the action's documentation, and it indicates that both `github-app` and `github-token` are optional.
This error began occurring after the recent update that added these parameters.
